# Generated by Django 5.2 on 2025-04-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(max_length=50, null='Unknown'),
            preserve_default='Unknown',
        ),
    ]
