# Generated by Django 5.2 on 2025-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50),
        ),
    ]
